package:
  name: busco
  version: "1.22"

build:
  number: 0
  skip: True # [osx]

source:
  fn: busco-v1.22.tar.gz
  url: http://busco.ezlab.org/files/BUSCO_v1.22.tar.gz
  md5: 9a5010c17ae0addffa18e5d169b0ff45

requirements:
  build:
    - python  
  run:
    - python
    - blast
    - hmmer
      #    - emboss

about:
  home: http://busco.ezlab.org/
  license: GPL
  summary: BUSCO provides measures for quantitative assessment of genome 
           assembly, gene set, and transcriptome completeness based on 
           evolutionarily informed expectations of gene content from 
           near-universal single-copy orthologs selected from OrthoDB. 

test:
  commands:
    - BUSCO_v1.22.py -h > /dev/null
    - busco -h > /dev/null
